import { Colors } from "./colors";

export interface FoodItem {
  id: string;
  name: string;
  moodTag: string;
  tagColor: string;
  tagTextColor: string;
  image: any;
}

export const FOOD_DATA: FoodItem[] = [
  {
    id: "1",
    name: "Nasi Goreng Merah",
    moodTag: "Netral",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/nasi_goreng_merah.png"),
  },
  {
    id: "2",
    name: "Mie Goreng Jakarta",
    moodTag: "Sedih",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/mie_goreng_jakarta.png"),
  },
  {
    id: "3",
    name: "Mie Kering / Titi",
    moodTag: "Senang",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/mie_kering.png"),
  },
  {
    id: "4",
    name: "Paket Ayam Geprek",
    moodTag: "Marah",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/paket_ayam_geprek.png"),
  },
  {
    id: "5",
    name: "Paket Telur Gimbal",
    moodTag: "Sedih",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/paket_telur_gimbal.png"),
  },
  {
    id: "6",
    name: "Beef Teriyaki",
    moodTag: "Senang",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/beef_teriyaki.png"),
  },
  {
    id: "7",
    name: "Beef Patty",
    moodTag: "Netral",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/beef_patty.png"),
  },
  {
    id: "8",
    name: "Kentang Goreng",
    moodTag: "Sedih",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/kentang_goreng.png"),
  },
  {
    id: "9",
    name: "Ubi Goreng",
    moodTag: "Senang",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/ubi_goreng.png"),
  },
  {
    id: "10",
    name: "Aneka Indomie",
    moodTag: "Marah",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/aneka_indomie.png"),
  },
  {
    id: "11",
    name: "Nasi Ayam Panggang",
    moodTag: "Netral",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/nasi_ayam_panggang.png"),
  },
  {
    id: "12",
    name: "Nasi Ayam Lengkuas",
    moodTag: "Sedih",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/nasi_ayam_lengkuas.png"),
  },
  {
    id: "13",
    name: "Mie Nyemek",
    moodTag: "Marah",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/mie_nyemek.png"),
  },
  {
    id: "14",
    name: "Mie Kering",
    moodTag: "Senang",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/mie_kering.png"),
  },
  {
    id: "15",
    name: "Mie Bakso",
    moodTag: "Netral",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/mie_bakso.png"),
  },
  {
    id: "16",
    name: "Mie Goreng Jawa",
    moodTag: "Sedih",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/mie_goreng_jawa.png"),
  },
  {
    id: "17",
    name: "Nasi Gila",
    moodTag: "Marah",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/nasi_gila.png"),
  },
  {
    id: "18",
    name: "Yamien",
    moodTag: "Senang",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/mie_yamien.png"),
  },
  {
    id: "19",
    name: "Tahu Crispy",
    moodTag: "Sedih",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/tahu_crispy.png"),
  },
  {
    id: "20",
    name: "Pisang Goreng",
    moodTag: "Senang",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/pisang_goreng.png"),
  },
  {
    id: "21",
    name: "Bakso Kuah",
    moodTag: "Sedih",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/bakso_kuah.png"),
  },
  {
    id: "22",
    name: "Nasi Goreng Jakarta",
    moodTag: "Netral",
    tagColor: Colors.third,
    tagTextColor: Colors.textPrimary,
    image: require("../assets/images/menu_makanan/nasi_goreng_jakarta.png"),
  },
];
